const LECTURA_CONTENT = {
 1: [ // B1 - Nivells 1-25 - 150 paraules aprox, vocabulari senzill
    {
      ca: "Fa molts anys, a la muntanya de Montserrat, vivia un pastor que cada dia pujava amb les seves ovelles. Un dia, mentre caminava entre les roques, va veure una llum molt forta que sortia d'una cova. El pastor va tenir por, però la curiositat era més gran. Quan va entrar a la cova, va trobar una estàtua de la Mare de Déu. La notícia va córrer ràpid per tots els pobles del voltant. La gent va començar a pujar a Montserrat per veure la Mare de Déu. Amb el temps, es va construir un monestir molt gran. Avui en dia, Montserrat és un lloc molt important per a Catalunya. Milers de persones hi van cada any per pregar, per caminar per les muntanyes o per escoltar el cor dels nens que canten. La llegenda diu que la Mare de Déu de Montserrat protegeix tothom qui la visita amb el cor net.",
      es: "Hace muchos años, en la montaña de Montserrat, vivía un pastor que cada día subía con sus ovejas. Un día, mientras caminaba entre las rocas, vio una luz muy fuerte que salía de una cueva. El pastor tuvo miedo, pero la curiosidad era más grande. Cuando entró en la cueva, encontró una estatua de la Virgen María. La noticia corrió rápido por todos los pueblos de alrededor. La gente empezó a subir a Montserrat para ver a la Virgen. Con el tiempo, se construyó un monasterio muy grande. Hoy en día, Montserrat es un lugar muy importante para Cataluña. Miles de personas van cada año para rezar, para caminar por las montañas o para escuchar el coro de los niños que cantan. La leyenda dice que la Virgen de Montserrat protege a todos los que la visitan con el corazón limpio.",
      en: "Many years ago, on Montserrat mountain, there lived a shepherd who went up every day with his sheep. One day, while walking among the rocks, he saw a very strong light coming from a cave. The shepherd was afraid, but his curiosity was greater. When he entered the cave, he found a statue of the Virgin Mary. The news spread quickly through all the nearby villages. People began to go up to Montserrat to see the Virgin. Over time, a very large monastery was built. Today, Montserrat is a very important place for Catalonia. Thousands of people go there every year to pray, to walk through the mountains or to listen to the children's choir sing. The legend says that the Virgin of Montserrat protects everyone who visits her with a clean heart."
    },
    {
      ca: "La història de Sant Jordi és molt famosa a Catalunya. Fa molt de temps, en un poble llunyà, hi havia un drac molt perillós. El drac vivia en una cova i cada dia sortia per menjar animals i persones. La gent del poble tenia molta por. Un dia, el rei va dir que calia donar al drac una persona cada dia per salvar els altres. Un dia va tocar el torn a la princesa. Just quan el drac anava a menjar-se-la, va arribar Sant Jordi amb el seu cavall. Sant Jordi era un cavaller valent. Va lluitar amb el drac i el va matar amb la seva espasa. De la sang del drac va néixer una rosa vermella molt bonica. Sant Jordi va donar la rosa a la princesa. Des d'aquell dia, el 23 d'abril, a Catalunya els homes regalen roses i les dones regalen llibres per celebrar Sant Jordi.",
      es: "La historia de Sant Jordi es muy famosa en Cataluña. Hace mucho tiempo, en un pueblo lejano, había un dragón muy peligroso. El dragón vivía en una cueva y cada día salía para comer animales y personas. La gente del pueblo tenía mucho miedo. Un día, el rey dijo que había que dar al dragón una persona cada día para salvar a los demás. Un día le tocó el turno a la princesa. Justo cuando el dragón iba a comérsela, llegó Sant Jordi con su caballo. Sant Jordi era un caballero valiente. Luchó con el dragón y lo mató con su espada. De la sangre del dragón nació una rosa roja muy bonita. Sant Jordi dio la rosa a la princesa. Desde aquel día, el 23 de abril, en Cataluña los hombres regalan rosas y las mujeres regalan libros para celebrar Sant Jordi.",
      en: "The story of Sant Jordi is very famous in Catalonia. A long time ago, in a distant village, there was a very dangerous dragon. The dragon lived in a cave and came out every day to eat animals and people. The village people were very afraid. One day, the king said they had to give the dragon one person each day to save the others. One day it was the princess's turn. Just when the dragon was about to eat her, Sant Jordi arrived on his horse. Sant Jordi was a brave knight. He fought the dragon and killed it with his sword. From the dragon's blood a very beautiful red rose was born. Sant Jordi gave the rose to the princess. Since that day, on April 23rd, in Catalonia men give roses and women give books to celebrate Sant Jordi."
    },
    {
      ca: "Girona és una ciutat molt antiga de Catalunya. El seu barri vell té carrers estrets de pedra que van daltabaix. Fa molts segles, els jueus vivien en un barri que es deia El Call. Encara avui es poden veure les cases antigues i els carrers laberíntics. Girona també és famosa pel riu Onyar. Al costat del riu hi ha cases pintades de colors groc, taronja i vermell. Quan el sol es pon, les cases es reflecteixen a l'aigua i fan un paisatge molt bonic. Molts pintors venen a Girona per dibuixar aquestes cases. La catedral de Girona és molt gran i té una escala enorme. Des de dalt es pot veure tota la ciutat. Girona ha sortit en pel·lícules i sèries de televisió perquè és molt bonica i ben conservada.",
      es: "Girona es una ciudad muy antigua de Cataluña. Su barrio viejo tiene calles estrechas de piedra que suben y bajan. Hace muchos siglos, los judíos vivían en un barrio que se llamaba El Call. Aún hoy se pueden ver las casas antiguas y las calles laberínticas. Girona también es famosa por el río Onyar. Al lado del río hay casas pintadas de color amarillo, naranja y rojo. Cuando el sol se pone, las casas se reflejan en el agua y crean un paisaje muy bonito. Muchos pintores vienen a Girona para dibujar estas casas. La catedral de Girona es muy grande y tiene una escalera enorme. Desde arriba se puede ver toda la ciudad. Girona ha salido en películas y series de televisión porque es muy bonita y bien conservada.",
      en: "Girona is a very old city in Catalonia. Its old town has narrow stone streets that go up and down. Many centuries ago, Jews lived in a neighborhood called El Call. Even today you can see the old houses and labyrinthine streets. Girona is also famous for the Onyar River. Next to the river there are houses painted yellow, orange and red. When the sun sets, the houses reflect in the water and create a very beautiful landscape. Many painters come to Girona to draw these houses. Girona Cathedral is very large and has a huge staircase. From the top you can see the whole city. Girona has appeared in movies and TV series because it is very beautiful and well preserved."
    },
    {
      ca: "Tossa de Mar és un poble de la Costa Brava amb una història molt llarga. Dalt d'un turó hi ha un castell medieval que es diu Vila Vella. El castell té muralles molt gruixudes per protegir el poble dels pirates. Fa molts anys, els pirates venien del mar per robar or i menjar. La gent de Tossa tancava les portes del castell i s'hi amagava. Des del castell es pot veure una platja d'arena fina i aigua blava. A l'estiu, molts turistes venen a nedar i prendre el sol. Tossa també és famosa perquè s'hi va rodar una pel·lícula americana fa molts anys. L'actriu Ava Gardner va viure aquí una temporada i va dir que Tossa era un paradís. Avui, Tossa és un lloc tranquil per passejar i menjar peix fresc.",
      es: "Tossa de Mar es un pueblo de la Costa Brava con una historia muy larga. En lo alto de una colina hay un castillo medieval que se llama Vila Vella. El castillo tiene murallas muy gruesas para proteger el pueblo de los piratas. Hace muchos años, los piratas venían del mar para robar oro y comida. La gente de Tossa cerraba las puertas del castillo y se escondía allí. Desde el castillo se puede ver una playa de arena fina y agua azul. En verano, muchos turistas vienen a nadar y tomar el sol. Tossa también es famosa porque se rodó una película americana aquí hace muchos años. La actriz Ava Gardner vivió aquí una temporada y dijo que Tossa era un paraíso. Hoy, Tossa es un lugar tranquilo para pasear y comer pescado fresco.",
      en: "Tossa de Mar is a town on the Costa Brava with a very long history. On top of a hill there is a medieval castle called Vila Vella. The castle has very thick walls to protect the town from pirates. Many years ago, pirates came from the sea to steal gold and food. The people of Tossa closed the castle gates and hid inside. From the castle you can see a beach of fine sand and blue water. In summer, many tourists come to swim and sunbathe. Tossa is also famous because an American movie was filmed here many years ago. Actress Ava Gardner lived here for a while and said Tossa was a paradise. Today, Tossa is a quiet place to walk and eat fresh fish."
    }
  ],

 2: [ // B2 - Nivells 26-75 - 170 paraules aprox, més detall
    {
      ca: "La llegenda de la Dama d'Aigua d'Estany és una de les històries més misterioses del llac de Banyoles. Diuen que al fons del llac viu una dona molt bonica que surt a la superfície quan hi ha lluna plena. Els pescadors antics explicaven que si veies la Dama, tenies bona sort per pescar aquell dia. Però també advertien que no havies d'apropar-te massa, perquè la Dama podia agafar-te la mà i arrossegar-te cap al fons. Ningú sap d'on ve aquesta llegenda, però els avis de Banyoles la contaven als seus nets cada nit. El llac de Banyoles és molt profund i l'aigua és tan clara que es veu el fons. Durant el dia, la gent va a nedar i a fer caiac. Però quan cau la nit, el llac es torna silenciós i misteriós. Alguns diuen que encara es pot veure l'ombra de la Dama si mires bé l'aigua sota la lluna.",
      es: "La leyenda de la Dama de Agua de Estany es una de las historias más misteriosas del lago de Bañolas. Dicen que en el fondo del lago vive una mujer muy bonita que sale a la superficie cuando hay luna llena. Los pescadores antiguos explicaban que si veías a la Dama, tenías buena suerte para pescar ese día. Pero también advertían que no te debías acercar demasiado, porque la Dama podía cogerte la mano y arrastrarte hacia el fondo. Nadie sabe de dónde viene esta leyenda, pero los abuelos de Bañolas la contaban a sus nietos cada noche. El lago de Bañolas es muy profundo y el agua es tan clara que se ve el fondo. Durante el día, la gente va a nadar y a hacer kayak. Pero cuando cae la noche, el lago se vuelve silencioso y misterioso. Algunos dicen que todavía se puede ver la sombra de la Dama si miras bien el agua bajo la luna.",
      en: "The legend of the Water Lady of Estany is one of the most mysterious stories of Banyoles Lake. They say that at the bottom of the lake lives a very beautiful woman who comes to the surface when there is a full moon. Ancient fishermen explained that if you saw the Lady, you would have good luck fishing that day. But they also warned that you should not get too close, because the Lady could take your hand and drag you to the bottom. No one knows where this legend comes from, but the grandparents of Banyoles told it to their grandchildren every night. Banyoles Lake is very deep and the water is so clear you can see the bottom. During the day, people go swimming and kayaking. But when night falls, the lake becomes silent and mysterious. Some say you can still see the Lady's shadow if you look closely at the water under the moon."
    },
    {
      ca: "Tarragona va ser una ciutat molt important durant l'època dels romans. Fa més de dos mil anys, els romans van construir aquí una ciutat que es deia Tarraco. Tarraco era la capital de tota la península Ibèrica. Els romans van construir un amfiteatre molt gran just davant del mar. A l'amfiteatre es feien lluites entre gladiadors i també curses de cavalls. La gent venia de pobles llunyans per veure els espectacles. Avui, l'amfiteatre encara està dempeus i es pot visitar. Quan estàs assegut a les grades, veus el mar blau darrere les pedres antigues. Tarragona també té un circ romà i muralles molt antigues. Caminar per Tarragona és com viatjar en el temps. La ciutat barreja història, mar i vida moderna.",
      es: "Tarragona fue una ciudad muy importante durante la época de los romanos. Hace más de dos mil años, los romanos construyeron aquí una ciudad que se llamaba Tarraco. Tarraco era la capital de toda la península Ibérica. Los romanos construyeron un anfiteatro muy grande justo frente al mar. En el anfiteatro se hacían luchas entre gladiadores y también carreras de caballos. La gente venía de pueblos lejanos para ver los espectáculos. Hoy, el anfiteatro aún sigue en pie y se puede visitar. Cuando estás sentado en las gradas, ves el mar azul detrás de las piedras antiguas. Tarragona también tiene un circo romano y murallas muy antiguas. Caminar por Tarragona es como viajar en el tiempo. La ciudad mezcla historia, mar y vida moderna.",
      en: "Tarragona was a very important city during Roman times. More than two thousand years ago, the Romans built a city here called Tarraco. Tarraco was the capital of the entire Iberian Peninsula. The Romans built a very large amphitheater right in front of the sea. In the amphitheater they held fights between gladiators and also horse races. People came from distant villages to see the shows. Today, the amphitheater is still standing and can be visited. When you sit in the stands, you see the blue sea behind the ancient stones. Tarragona also has a Roman circus and very old walls. Walking through Tarragona is like traveling through time. The city mixes history, sea and modern life."
    },
    {
      ca: "El calçot és un tipus de ceba llarga que es menja sobretot a Valls i al Camp de Tarragona. La tradició del calçotada va començar fa més de cent anys. Un pagès de Valls va inventar la manera de coure els calçots a la brasa i menjar-los amb salsa romesco. La salsa romesco porta tomàquet, ametlles, avellanes i nyora. Quan arriba l'hivern, la gent de tota Catalunya va a Valls per fer calçotades. Es reuneixen grups d'amics i família al voltant d'una taula llarga a l'aire lliure. Primer es mengen els calçots agafant-los amb la mà i sucat-los amb la salsa. Després es menja carn a la brasa, mongetes i carxofes. Tot acaba amb crema catalana de postres. La calçotada és més que menjar, és una festa per compartir amb la gent que estimes.",
      es: "El calçot es un tipo de cebolla larga que se come sobre todo en Valls y en el Campo de Tarragona. La tradición de la calçotada empezó hace más de cien años. Un campesino de Valls inventó la manera de cocer los calçots a la brasa y comerlos con salsa romesco. La salsa romesco lleva tomate, almendras, avellanas y ñora. Cuando llega el invierno, la gente de toda Cataluña va a Valls para hacer calçotadas. Se reúnen grupos de amigos y familia alrededor de una mesa larga al aire libre. Primero se comen los calçots cogiéndolos con la mano y mojándolos con la salsa. Después se come carne a la brasa, alubias y alcachofas. Todo acaba con crema catalana de postre. La calçotada es más que comida, es una fiesta para compartir con la gente que quieres.",
      en: "Calçot is a type of long onion that is eaten mainly in Valls and the Camp de Tarragona. The calçotada tradition began more than a hundred years ago. A farmer from Valls invented the way to grill calçots over coals and eat them with romesco sauce. Romesco sauce has tomato, almonds, hazelnuts and ñora pepper. When winter comes, people from all over Catalonia go to Valls for calçotadas. Groups of friends and family gather around a long table outdoors. First they eat the calçots by hand, dipping them in the sauce. Then they eat grilled meat, beans and artichokes. It all ends with crema catalana for dessert. A calçotada is more than food, it is a celebration to share with the people you love."
    },
    {
      ca: "Cadaqués és un poble de pescadors a la Costa Brava que ha inspirat molts pintors. La llum de Cadaqués és especial, molt clara i brillant. Salvador Dalí va néixer a Figueres, que està a prop, i va passar molts estius a Cadaqués. La seva casa a Portlligat està oberta al públic i es pot visitar. Dalí deia que Cadaqués era el millor lloc del món per pintar. Les cases blanques del poble contrasten amb el mar blau i les roques grises. Quan el sol es pon, el cel es torna de color rosa i taronja. Els artistes venen aquí per capturar aquesta llum única. Cadaqués també té cales petites on es pot nedar en aigua cristal·lina. Caminar pels carrers estrets de Cadaqués és com entrar en un quadre.",
      es: "Cadaqués es un pueblo de pescadores en la Costa Brava que ha inspirado a muchos pintores. La luz de Cadaqués es especial, muy clara y brillante. Salvador Dalí nació en Figueres, que está cerca, y pasó muchos veranos en Cadaqués. Su casa en Portlligat está abierta al público y se puede visitar. Dalí decía que Cadaqués era el mejor lugar del mundo para pintar. Las casas blancas del pueblo contrastan con el mar azul y las rocas grises. Cuando el sol se pone, el cielo se vuelve de color rosa y naranja. Los artistas vienen aquí para capturar esta luz única. Cadaqués también tiene calas pequeñas donde se puede nadar en agua cristalina. Caminar por las calles estrechas de Cadaqués es como entrar en un cuadro.",
      en: "Cadaqués is a fishing village on the Costa Brava that has inspired many painters. The light in Cadaqués is special, very clear and bright. Salvador Dalí was born in Figueres, which is nearby, and spent many summers in Cadaqués. His house in Portlligat is open to the public and can be visited. Dalí said Cadaqués was the best place in the world to paint. The white houses of the village contrast with the blue sea and gray rocks. When the sun sets, the sky turns pink and orange. Artists come here to capture this unique light. Cadaqués also has small coves where you can swim in crystal clear water. Walking through the narrow streets of Cadaqués is like stepping into a painting."
    }
  ],

 3: [ // C1 - Nivells 76-100 - 180-200 paraules, narrativa rica
    {
      ca: "El sincrotró ALBA, situat al Parc de l'Alba de Cerdanyola del Vallès, és una de les infraestructures científiques més avançades del sud d'Europa. Aquest accelerador de partícules genera llum de raigs X extremadament brillant que permet als científics observar la matèria a escala atòmica. Gràcies a ALBA, investigadors de tot el món estudien proteïnes per crear nous medicaments contra el càncer i altres malalties. També analitzen materials antics per entendre com vivien els nostres avantpassats. La instal·lació té forma de cercle de més de dos-cents metres de diàmetre i funciona dia i nit. Centenars de científics treballen aquí en projectes de física, química, biologia i arqueologia. ALBA és un exemple de com Catalunya aposta per la ciència i la innovació. Visitar ALBA és entendre com la tecnologia més moderna pot ajudar a resoldre problemes humans i millorar la vida de tothom.",
      es: "El sincrotrón ALBA, situado en el Parc de l'Alba de Cerdanyola del Vallès, es una de las infraestructuras científicas más avanzadas del sur de Europa. Este acelerador de partículas genera luz de rayos X extremadamente brillante que permite a los científicos observar la materia a escala atómica. Gracias a ALBA, investigadores de todo el mundo estudian proteínas para crear nuevos medicamentos contra el cáncer y otras enfermedades. También analizan materiales antiguos para entender cómo vivían nuestros antepasados. La instalación tiene forma de círculo de más de doscientos metros de diámetro y funciona día y noche. Cientos de científicos trabajan aquí en proyectos de física, química, biología y arqueología. ALBA es un ejemplo de cómo Cataluña apuesta por la ciencia y la innovación. Visitar ALBA es entender cómo la tecnología más moderna puede ayudar a resolver problemas humanos y mejorar la vida de todos.",
      en: "The ALBA synchrotron, located in the Parc de l'Alba in Cerdanyola del Vallès, is one of the most advanced scientific infrastructures in southern Europe. This particle accelerator generates extremely bright X-ray light that allows scientists to observe matter at the atomic scale. Thanks to ALBA, researchers from around the world study proteins to create new medicines against cancer and other diseases. They also analyze ancient materials to understand how our ancestors lived. The facility is shaped like a circle more than two hundred meters in diameter and operates day and night. Hundreds of scientists work here on projects in physics, chemistry, biology and archaeology. ALBA is an example of how Catalonia bets on science and innovation. Visiting ALBA is understanding how the most modern technology can help solve human problems and improve everyone's life."
    },
    {
      ca: "El Parc Nacional d'Aigüestortes i Estany de Sant Maurici és un tresor natural situat al cor dels Pirineus catalans. Aquest parc protegeix més de dos-cents llacs d'origen glacial, cascades impressionants i boscos de pi negre que tenen centenars d'anys. El nom 'Aigüestortes' significa 'aigües tortes' en català, perquè els rius formen meandres i salts d'aigua molt bonics. El parc és la llar del trencalòs, una au rapinyaire gegant que estava a punt d'extingir-se però que ara es recupera gràcies als programes de protecció. També hi viuen isards, marmotes i cérvols. Cada estiu, milers de senderistes recorren els camins del parc per gaudir de la natura pura. L'aire és net, el silenci és profund i les vistes són espectaculars. Aigüestortes és un recordatori de com de bonica és la muntanya catalana quan es respecta i es protegeix.",
      es: "El Parque Nacional de Aigüestortes y Lago de San Mauricio es un tesoro natural situado en el corazón de los Pirineos catalanes. Este parque protege más de doscientos lagos de origen glacial, cascadas impresionantes y bosques de pino negro que tienen cientos de años. El nombre 'Aigüestortes' significa 'aguas torcidas' en catalán, porque los ríos forman meandros y saltos de agua muy bonitos. El parque es el hogar del quebrantahuesos, un ave rapaz gigante que estaba a punto de extinguirse pero que ahora se recupera gracias a los programas de protección. También viven sarrios, marmotas y ciervos. Cada verano, miles de senderistas recorren los caminos del parque para disfrutar de la naturaleza pura. El aire es limpio, el silencio es profundo y las vistas son espectaculares. Aigüestortes es un recordatorio de lo bonita que es la montaña catalana cuando se respeta y se protege.",
      en: "The Aigüestortes and Lake Sant Maurici National Park is a natural treasure located in the heart of the Catalan Pyrenees. This park protects more than two hundred glacial lakes, impressive waterfalls and black pine forests that are hundreds of years old. The name 'Aigüestortes' means 'twisted waters' in Catalan, because the rivers form meanders and beautiful waterfalls. The park is home to the bearded vulture, a giant bird of prey that was on the verge of extinction but is now recovering thanks to protection programs. Ibex, marmots and deer also live here. Every summer, thousands of hikers walk the park's trails to enjoy pure nature. The air is clean, the silence is deep and the views are spectacular. Aigüestortes is a reminder of how beautiful the Catalan mountains are when they are respected and protected."
    },
    {
      ca: "Les Illes Medes són un arxipèlag de set illots situat davant de la costa de l'Estartit, a la Costa Brava. Des de l'any 1983 són una reserva marina protegida, cosa que ha permès que la vida submarina s'hi desenvolupi de manera excepcional. Sota l'aigua hi ha prats de posidònia, gorgònies gegants, corall vermell i una gran varietat de peixos de colors. El fons marí de les Medes és considerat un dels millors llocs per bussejar de tot el Mediterrani. Els bussejadors poden veure mero, llobarro, sargo i fins i tot taurons petits que no són perillosos. La pesca està prohibida per protegir l'ecosistema. Els científics estudien les Medes per entendre com el canvi climàtic afecta el mar. Des de terra, es poden veure les illes i imaginar el món secret que hi ha sota l'aigua blava.",
      es: "Las Islas Medas son un archipiélago de siete islotes situado frente a la costa del Estartit, en la Costa Brava. Desde el año 1983 son una reserva marina protegida, lo que ha permitido que la vida submarina se desarrolle de manera excepcional. Bajo el agua hay praderas de posidonia, gorgonias gigantes, coral rojo y una gran variedad de peces de colores. El fondo marino de las Medas es considerado uno de los mejores lugares para bucear de todo el Mediterráneo. Los buceadores pueden ver mero, lubina, sargo e incluso tiburones pequeños que no son peligrosos. La pesca está prohibida para proteger el ecosistema. Los científicos estudian las Medas para entender cómo el cambio climático afecta al mar. Desde tierra, se pueden ver las islas e imaginar el mundo secreto que hay bajo el agua azul.",
      en: "The Medes Islands are an archipelago of seven islets located off the coast of l'Estartit, on the Costa Brava. Since 1983 they have been a protected marine reserve, which has allowed underwater life to develop exceptionally. Underwater there are seagrass meadows, giant gorgonians, red coral and a great variety of colorful fish. The seabed of the Medes is considered one of the best diving spots in the entire Mediterranean. Divers can see grouper, sea bass, bream and even small sharks that are not dangerous. Fishing is prohibited to protect the ecosystem. Scientists study the Medes to understand how climate change affects the sea. From land, you can see the islands and imagine the secret world under the blue water."
    },
    {
      ca: "Reus és la ciutat on va néixer Antoni Gaudí, l'arquitecte més genial de Catalunya. Gaudí va passar la seva infantesa a Reus abans de marxar a Barcelona per estudiar arquitectura. La ciutat conserva molts edificis modernistes del segle XIX, quan Reus era rica gràcies al comerç de vi i aiguardent. El modernisme reusenc es veu en les façanes decorades amb ferro forjat, ceràmica de colors i vitralls. A més de l'arquitectura, Reus és famosa pel seu vermut artesà. La tradició vermutera va començar fa més de cent anys i encara continua viva. Hi ha bars antics on la gent es reuneix per prendre vermut amb olives i patates fregides. El vermut de Reus s'exporta a tot el món. Caminar per Reus és descobrir una ciutat elegant, culta i amb una identitat molt marcada.",
      es: "Reus es la ciudad donde nació Antoni Gaudí, el arquitecto más genial de Cataluña. Gaudí pasó su infancia en Reus antes de marcharse a Barcelona para estudiar arquitectura. La ciudad conserva muchos edificios modernistas del siglo XIX, cuando Reus era rica gracias al comercio de vino y aguardiente. El modernismo reusense se ve en las fachadas decoradas con hierro forjado, cerámica de colores y vitrales. Además de la arquitectura, Reus es famosa por su vermut artesano. La tradición vermutera empezó hace más de cien años y aún continúa viva. Hay bares antiguos donde la gente se reúne para tomar vermut con aceitunas y patatas fritas. El vermut de Reus se exporta a todo el mundo. Caminar por Reus es descubrir una ciudad elegante, culta y con una identidad muy marcada.",
      en: "Reus is the city where Antoni Gaudí was born, the most brilliant architect of Catalonia. Gaudí spent his childhood in Reus before moving to Barcelona to study architecture. The city preserves many 19th-century modernist buildings, when Reus was wealthy thanks to wine and brandy trade. Reus modernism can be seen in facades decorated with wrought iron, colorful ceramics and stained glass. Besides architecture, Reus is famous for its artisan vermouth. The vermouth tradition began more than a hundred years ago and is still alive. There are old bars where people gather to drink vermouth with olives and potato chips. Reus vermouth is exported all over the world. Walking through Reus is discovering an elegant, cultured city with a very strong identity."
    }
  ]
};
