// tips-data.js v3.0 - Paraula Ràpida
// 20 tips per bloc: Gramàtica, Vocabulari, Cultura. Nivells B1-B2-B3. Rotatius + Quiz "Contestar"

const TIPS_DATA = {
  gramatica: [
    // NIVELL 1 - B1
    {id: "g1", nivell: 1, ca: {titol: "Article 'el/la'", text: "En català sempre posem l'article davant del nom: el gos, la casa, el cotxe."}, es: {titol: "Artículo 'el/la'", text: "En catalán siempre ponemos el artículo delante del nombre: el gos, la casa, el cotxe."}, en: {titol: "Article 'el/la'", text: "In Catalan we always use the article before the noun: el gos, la casa, el cotxe."}},
    {id: "g2", nivell: 1, ca: {titol: "Preposició 'a'", text: "'A' indica direcció o ubicació: Vaig a l'escola, Estic a casa, Anem a Barcelona."}, es: {titol: "Preposición 'a'", text: "'A' indica dirección o ubicación: Vaig a l'escola, Estic a casa, Anem a Barcelona."}, en: {titol: "Preposition 'a'", text: "'A' shows direction or location: Vaig a l'escola, Estic a casa, Anem a Barcelona."}},
    {id: "g3", nivell: 1, ca: {titol: "Verb 'estar' + adjectiu", text: "'Estar' descriu estats temporals: Estic content, Estàs cansat, Estem feliços."}, es: {titol: "Verbo 'estar' + adjetivo", text: "'Estar' describe estados temporales: Estic content, Estàs cansat, Estem feliços."}, en: {titol: "Verb 'estar' + adjective", text: "'Estar' describes temporary states: Estic content, Estàs cansat, Estem feliços."}},
    {id: "g4", nivell: 1, ca: {titol: "Plurals regulars", text: "Afegim -s: casa → cases, llibre → llibres. Si acaba en vocal tònica: cafè → cafès."}, es: {titol: "Plurales regulares", text: "Añadimos -s: casa → cases, llibre → llibres. Si acaba en vocal tónica: cafè → cafès."}, en: {titol: "Regular plurals", text: "Add -s: casa → cases, llibre → llibres. If ends in stressed vowel: cafè → cafès."}},
    {id: "g5", nivell: 1, ca: {titol: "Gènere masculí/femení", text: "El/la: el noi, la noia. O/a: el gat, la gata. -e neutre: el professor, la professora."}, es: {titol: "Género masculino/femenino", text: "El/la: el noi, la noia. O/a: el gat, la gata. -e neutro: el professor, la professora."}, en: {titol: "Masculine/feminine gender", text: "El/la: el noi, la noia. O/a: el gat, la gata. -e neutral: el professor, la professora."}},
    {id: "g6", nivell: 1, ca: {titol: "Demostratius", text: "Aquest/a = this, Aquell/a = that: Aquest llibre, Aquella casa. Acorda amb gènere i nombre."}, es: {titol: "Demostrativos", text: "Aquest/a = this, Aquell/a = that: Aquest llibre, Aquella casa. Concuerda en género y número."}, en: {titol: "Demonstratives", text: "Aquest/a = this, Aquell/a = that: Aquest llibre, Aquella casa. Agrees in gender and number."}},
    {id: "g7", nivell: 1, ca: {titol: "Negació 'no'", text: "Posem 'no' davant del verb: No parlo català, No menjo carn. Doble negació: No vull res."}, es: {titol: "Negación 'no'", text: "Ponemos 'no' delante del verbo: No parlo català, No menjo carn. Doble negación: No vull res."}, en: {titol: "Negation 'no'", text: "Put 'no' before the verb: No parlo català, No menjo carn. Double negation: No vull res."}},
    {id: "g8", nivell: 1, ca: {titol: "Preguntes amb 'què'", text: "Què fas? Què és això? Què vols? 'Què' sempre va al principi de la pregunta."}, es: {titol: "Preguntas con 'qué'", text: "Què fas? Què és això? Què vols? 'Què' siempre va al principio de la pregunta."}, en: {titol: "Questions with 'what'", text: "Què fas? Què és això? Què vols? 'Què' always goes at the start."}},

    // NIVELL 2 - B2
    {id: "g9", nivell: 2, ca: {titol: "Jugar a + esport", text: "El verb 'jugar' sempre va amb 'a': Jugo a futbol, Jugues a bàsquet, Juguen a tennis."}, es: {titol: "Jugar a + deporte", text: "El verbo 'jugar' siempre va con 'a': Jugo a futbol, Jugues a bàsquet, Juguen a tennis."}, en: {titol: "Play + sport", text: "The verb 'jugar' always uses 'a': Jugo a futbol, Jugues a bàsquet, Juguen a tennis."}},
    {id: "g10", nivell: 2, ca: {titol: "Treballar de + professió", text: "Per dir la professió usem 'treballar de': Treballo de mestre, Treballa de cuinera."}, es: {titol: "Trabajar de + profesión", text: "Para decir la profesión usamos 'treballar de': Treballo de mestre, Treballa de cuinera."}, en: {titol: "Work as + profession", text: "To say profession we use 'treballar de': Treballo de mestre, Treballa de cuinera."}},
    {id: "g11", nivell: 2, ca: {titol: "Passat perifràstic", text: "Per accions acabades: Vaig anar, Vam menjar, Vas veure. Estructura: anar + infinitiu."}, es: {titol: "Pasado perifrástico", text: "Para acciones acabadas: Vaig anar, Vam menjar, Vas veure. Estructura: anar + infinitivo."}, en: {titol: "Periphrastic past", text: "For finished actions: Vaig anar, Vam menjar, Vas veure. Structure: anar + infinitive."}},
    {id: "g12", nivell: 2, ca: {titol: "Futur amb 'anar a'", text: "Per parlar del futur: Vaig a estudiar, Anem a dinar, Anirà a Barcelona. Més natural que el futur simple."}, es: {titol: "Futuro con 'ir a'", text: "Para hablar del futuro: Vaig a estudiar, Anem a dinar, Anirà a Barcelona. Más natural que el futuro simple."}, en: {titol: "Future with 'go to'", text: "For future: Vaig a estudiar, Anem a dinar, Anirà a Barcelona. More natural than simple future."}},
    {id: "g13", nivell: 2, ca: {titol: "Pronoms febles 'el/la'", text: "Objecte directe abans del verb: El veig, La conec, Els truco. Sempre abans del verb conjugat."}, es: {titol: "Pronombres débiles 'lo/la'", text: "Objeto directo antes del verbo: El veig, La conec, Els truco. Siempre antes del verbo conjugado."}, en: {titol: "Weak pronouns 'him/her'", text: "Direct object before verb: El veig, La conec, Els truco. Always before conjugated verb."}},
    {id: "g14", nivell: 2, ca: {titol: "Comparatius", text: "Més... que, Menys... que, Tan... com: Més alt que tu, Tan intel·ligent com ella."}, es: {titol: "Comparativos", text: "Més... que, Menys... que, Tan... com: Més alt que tu, Tan intel·ligent com ella."}, en: {titol: "Comparatives", text: "Més... que, Menys... que, Tan... com: Més alt que tu, Tan intel·ligent com ella."}},
    {id: "g15", nivell: 2, ca: {titol: "Superlatiu 'el més'", text: "Per dir el grau màxim: El més bonic, La més ràpida, Els més intel·ligents. Article + més + adjectiu."}, es: {titol: "Superlativo 'el más'", text: "Para decir el grado máximo: El més bonic, La més ràpida, Els més intel·ligents. Artículo + més + adjetivo."}, en: {titol: "Superlative 'the most'", text: "For maximum degree: El més bonic, La més ràpida, Els més intel·ligents. Article + més + adjective."}},

    // NIVELL 3 - B3
    {id: "g16", nivell: 3, ca: {titol: "Mentre + subjuntiu", text: "'Mentre' indica accions simultànies: Escolto música mentre cuino, Llegeix mentre viatja."}, es: {titol: "Mientras + subjuntivo", text: "'Mentre' indica acciones simultáneas: Escolto música mentre cuino, Llegeix mentre viatja."}, en: {titol: "While + subjunctive", text: "'Mentre' indicates simultaneous actions: Escolto música mentre cuino, Llegeix mentre viatja."}},
    {id: "g17", nivell: 3, ca: {titol: "Condicional 'si'", text: "Si + present, futur: Si estudio, aprovaré. Si + imperfet, condicional: Si estudiava, aprovaria."}, es: {titol: "Condicional 'si'", text: "Si + presente, futuro: Si estudio, aprovaré. Si + imperfecto, condicional: Si estudiava, aprovaria."}, en: {titol: "Conditional 'if'", text: "Si + present, future: Si estudio, aprovaré. Si + imperfect, conditional: Si estudiava, aprovaria."}},
    {id: "g18", nivell: 3, ca: {titol: "Subjuntiu present", text: "Per desig, dubte, necessitat: Vull que vinguis, Dubto que plogui, Cal que estudiem. Canvia la terminació del verb."}, es: {titol: "Subjuntivo presente", text: "Para deseo, duda, necesidad: Vull que vinguis, Dubto que plogui, Cal que estudiem. Cambia la terminación del verbo."}, en: {titol: "Present subjunctive", text: "For wish, doubt, necessity: Vull que vinguis, Dubto que plogui, Cal que estudiem. Verb ending changes."}},
    {id: "g19", nivell: 3, ca: {titol: "Pronoms relatius 'que/qui'", text: "'Que' per coses: El llibre que llegeixo. 'Qui' per persones: La noia qui parla. No s'ometen com en castellà."}, es: {titol: "Pronombres relativos 'que/quien'", text: "'Que' para cosas: El llibre que llegeixo. 'Qui' para personas: La noia qui parla. No se omiten como en castellano."}, en: {titol: "Relative pronouns 'that/who'", text: "'Que' for things: El llibre que llegeixo. 'Qui' for people: La noia qui parla. Not omitted like in Spanish."}},
    {id: "g20", nivell: 3, ca: {titol: "Passiva reflexiva 'es'", text: "Per accions impersonals: Es parla català, Es venen llibres, Es diu que... Molt usat en català escrit."}, es: {titol: "Pasiva refleja 'se'", text: "Para acciones impersonales: Es parla català, Es venen llibres, Es diu que... Muy usado en catalán escrito."}, en: {titol: "Reflexive passive 'es'", text: "For impersonal actions: Es parla català, Es venen llibres, Es diu que... Very common in written Catalan."}}
  ],

  vocabulari: [
    // NIVELL 1 - B1
    {id: "v1", nivell: 1, ca: {titol: "Salutacions", text: "Bon dia, Bona tarda, Bona nit. Hola! Com estàs? Estic bé, gràcies. Adéu, fins aviat!"}, es: {titol: "Saludos", text: "Bon dia, Bona tarda, Bona nit. Hola! Com estàs? Estic bé, gràcies. Adéu, fins aviat!"}, en: {titol: "Greetings", text: "Bon dia, Bona tarda, Bona nit. Hola! Com estàs? Estic bé, gràcies. Adéu, fins aviat!"}},
    {id: "v2", nivell: 1, ca: {titol: "Números 1-20", text: "Un, dos, tres, quatre, cinc, sis, set, vuit, nou, deu, onze, dotze, tretze, catorze, quinze, setze, disset, divuit, dinou, vint."}, es: {titol: "Números 1-20", text: "Un, dos, tres, quatre, cinc, sis, set, vuit, nou, deu, onze, dotze, tretze, catorze, quinze, setze, disset, divuit, dinou, vint."}, en: {titol: "Numbers 1-20", text: "Un, dos, tres, quatre, cinc, sis, set, vuit, nou, deu, onze, dotze, tretze, catorze, quinze, setze, disset, divuit, dinou, vint."}},
    {id: "v3", nivell: 1, ca: {titol: "Colors bàsics", text: "Vermell, blau, verd, groc, negre, blanc, rosa, marró, gris, taronja, lila, morat."}, es: {titol: "Colores básicos", text: "Vermell, blau, verd, groc, negre, blanc, rosa, marró, gris, taronja, lila, morat."}, en: {titol: "Basic colors", text: "Vermell, blau, verd, groc, negre, blanc, rosa, marró, gris, taronja, lila, morat."}},
    {id: "v4", nivell: 1, ca: {titol: "Dies de la setmana", text: "Dilluns, dimarts, dimecres, dijous, divendres, dissabte, diumenge. El cap de setmana."}, es: {titol: "Días de la semana", text: "Dilluns, dimarts, dimecres, dijous, divendres, dissabte, diumenge. El cap de setmana."}, en: {titol: "Days of the week", text: "Dilluns, dimarts, dimecres, dijous, divendres, dissabte, diumenge. El cap de setmana."}},
    {id: "v5", nivell: 1, ca: {titol: "Parts del cos", text: "Cap, ulls, nas, boca, orella, mà, braç, cama, peu, esquena, panxa, cor."}, es: {titol: "Partes del cuerpo", text: "Cap, ulls, nas, boca, orella, mà, braç, cama, peu, esquena, panxa, cor."}, en: {titol: "Body parts", text: "Cap, ulls, nas, boca, orella, mà, braç, cama, peu, esquena, panxa, cor."}},
    {id: "v6", nivell: 1, ca: {titol: "Família bàsica", text: "Pare, mare, germà, germana, avi, àvia, fill, filla, marit, muller, cosí, cosina."}, es: {titol: "Familia básica", text: "Pare, mare, germà, germana, avi, àvia, fill, filla, marit, muller, cosí, cosina."}, en: {titol: "Basic family", text: "Pare, mare, germà, germana, avi, àvia, fill, filla, marit, muller, cosí, cosina."}},
    {id: "v7", nivell: 1, ca: {titol: "Menjar bàsic", text: "Pa, aigua, llet, carn, peix, verdura, fruita, arròs, pasta, formatge, ou, sucre."}, es: {titol: "Comida básica", text: "Pa, aigua, llet, carn, peix, verdura, fruita, arròs, pasta, formatge, ou, sucre."}, en: {titol: "Basic food", text: "Pa, aigua, llet, carn, peix, verdura, fruita, arròs, pasta, formatge, ou, sucre."}},

    // NIVELL 2 - B2
    {id: "v8", nivell: 2, ca: {titol: "Menjar català", text: "Pa amb tomàquet, calçots, escudella, fideuà, crema catalana, botifarra, samfaina. Bon profit!"}, es: {titol: "Comida catalana", text: "Pa amb tomàquet, calçots, escudella, fideuà, crema catalana, botifarra, samfaina. Bon profit!"}, en: {titol: "Catalan food", text: "Pa amb tomàquet, calçots, escudella, fideuà, crema catalana, botifarra, samfaina. Bon profit!"}},
    {id: "v9", nivell: 2, ca: {titol: "Transports", text: "Autobús, tren, metro, avió, bicicleta, cotxe, moto, vaixell, tramvia, taxi, funicular."}, es: {titol: "Transportes", text: "Autobús, tren, metro, avió, bicicleta, cotxe, moto, vaixell, tramvia, taxi, funicular."}, en: {titol: "Transport", text: "Autobús, tren, metro, avió, bicicleta, cotxe, moto, vaixell, tramvia, taxi, funicular."}},
    {id: "v10", nivell: 2, ca: {titol: "Professions", text: "Mestre, metge, cuiner, mecànic, astronauta, artista, advocat, infermera, paleta, electricista."}, es: {titol: "Profesiones", text: "Mestre, metge, cuiner, mecànic, astronauta, artista, advocat, infermera, paleta, electricista."}, en: {titol: "Professions", text: "Mestre, metge, cuiner, mecànic, astronauta, artista, advocat, infermera, paleta, electricista."}},
    {id: "v11", nivell: 2, ca: {titol: "Llocs de la ciutat", text: "Biblioteca, hospital, escola, parc, museu, mercat, estació, església, restaurant, teatre, plaça."}, es: {titol: "Lugares de la ciudad", text: "Biblioteca, hospital, escola, parc, museu, mercat, estació, església, restaurant, teatre, plaça."}, en: {titol: "City places", text: "Biblioteca, hospital, escola, parc, museu, mercat, estació, església, restaurant, teatre, plaça."}},
    {id: "v12", nivell: 2, ca: {titol: "El temps", text: "Sol, pluja, neu, vent, núvols, tempesta, arc de Sant Martí, calor, fred, humitat, boira, gebre."}, es: {titol: "El tiempo", text: "Sol, pluja, neu, vent, núvols, tempesta, arc de Sant Martí, calor, fred, humitat, boira, gebre."}, en: {titol: "Weather", text: "Sol, pluja, neu, vent, núvols, tempesta, arc de Sant Martí, calor, fred, humitat, boira, gebre."}},
    {id: "v13", nivell: 2, ca: {titol: "Roba i accessoris", text: "Camisa, pantaló, vestit, sabates, jaqueta, barret, bufanda, guants, bossa, ulleres, rellotge."}, es: {titol: "Ropa y accesorios", text: "Camisa, pantaló, vestit, sabates, jaqueta, barret, bufanda, guants, bossa, ulleres, rellotge."}, en: {titol: "Clothes and accessories", text: "Camisa, pantaló, vestit, sabates, jaqueta, barret, bufanda, guants, bossa, ulleres, rellotge."}},

    // NIVELL 3 - B3
    {id: "v14", nivell: 3, ca: {titol: "Tecnologia", text: "Ordinador, mòbil, tauleta, internet, aplicació, correu electrònic, xarxes socials, wifi, bluetooth, pantalla."}, es: {titol: "Tecnología", text: "Ordinador, mòbil, tauleta, internet, aplicació, correu electrònic, xarxes socials, wifi, bluetooth, pantalla."}, en: {titol: "Technology", text: "Ordinador, mòbil, tauleta, internet, aplicació, correu electrònic, xarxes socials, wifi, bluetooth, pantalla."}},
    {id: "v15", nivell: 3, ca: {titol: "Sentiments complexos", text: "Nostàlgia, enveja, orgull, vergonya, il·lusió, ansietat, gratitud, compassió, frustració, esperança."}, es: {titol: "Sentimientos complejos", text: "Nostàlgia, enveja, orgull, vergonya, il·lusió, ansietat, gratitud, compassió, frustració, esperança."}, en: {titol: "Complex feelings", text: "Nostàlgia, enveja, orgull, vergonya, il·lusió, ansietat, gratitud, compassió, frustració, esperança."}},
    {id: "v16", nivell: 3, ca: {titol: "Política i societat", text: "Govern, eleccions, partit, democràcia, llibertat, justícia, economia, educació, sanitat, medi ambient."}, es: {titol: "Política y sociedad", text: "Govern, eleccions, partit, democràcia, llibertat, justícia, economia, educació, sanitat, medi ambient."}, en: {titol: "Politics and society", text: "Govern, eleccions, partit, democràcia, llibertat, justícia, economia, educació, sanitat, medi ambient."}},
    {id: "v17", nivell: 3, ca: {titol: "Verbs de moviment", text: "Anar, venir, pujar, baixar, entrar, sortir, passar, travessar, girar, acostar-se, allunyar-se, arribar."}, es: {titol: "Verbos de movimiento", text: "Anar, venir, pujar, baixar, entrar, sortir, passar, travessar, girar, acostar-se, allunyar-se, arribar."}, en: {titol: "Movement verbs", text: "Anar, venir, pujar, baixar, entrar, sortir, passar, travessar, girar, acostar-se, allunyar-se, arribar."}},
    {id: "v18", nivell: 3, ca: {titol: "Adjectius descriptius", text: "Intel·ligent, divertit, simpàtic, treballador, pacient, valent, generós, sincer, creatiu, responsable, amable."}, es: {titol: "Adjetivos descriptivos", text: "Intel·ligent, divertit, simpàtic, treballador, pacient, valent, generós, sincer, creatiu, responsable, amable."}, en: {titol: "Descriptive adjectives", text: "Intel·ligent, divertit, simpàtic, treballador, pacient, valent, generós, sincer, creatiu, responsable, amable."}},
    {id: "v19", nivell: 3, ca: {titol: "Arts i cultura", text: "Pintura, escultura, música, dansa, teatre, literatura, poesia, cinema, fotografia, arquitectura."}, es: {titol: "Artes y cultura", text: "Pintura, escultura, música, dansa, teatre, literatura, poesia, cinema, fotografia, arquitectura."}, en: {titol: "Arts and culture", text: "Pintura, escultura, música, dansa, teatre, literatura, poesia, cinema, fotografia, arquitectura."}},
    {id: "v20", nivell: 3, ca: {titol: "Connectors avançats", text: "Per tant, a més, no obstant, en canvi, tot i que, malgrat, a causa de, gràcies a, en conseqüència, per exemple."}, es: {titol: "Conectores avanzados", text: "Per tant, a més, no obstant, en canvi, tot i que, malgrat, a causa de, gràcies a, en conseqüència, per exemple."}, en: {titol: "Advanced connectors", text: "Per tant, a més, no obstant, en canvi, tot i que, malgrat, a causa de, gràcies a, en conseqüència, per exemple."}}
  ],

  cultura: [
    // NIVELL 1 - B1
    {id: "c1", nivell: 1, ca: {titol: "Barcelona", text: "Barcelona és la capital de Catalunya. Té la Sagrada Família, el Parc Güell i la platja. Molt turística."}, es: {titol: "Barcelona", text: "Barcelona és la capital de Catalunya. Té la Sagrada Família, el Parc Güell i la platja. Molt turística."}, en: {titol: "Barcelona", text: "Barcelona is the capital of Catalonia. It has the Sagrada Família, Parc Güell and the beach. Very touristic."}},
    {id: "c2", nivell: 1, ca: {titol: "Llengua catalana", text: "El català es parla a Catalunya, València, Balears, Andorra i part d'Aragó. 10 milions de parlants."}, es: {titol: "Lengua catalana", text: "El català es parla a Catalunya, València, Balears, Andorra i part d'Aragó. 10 milions de parlants."}, en: {titol: "Catalan language", text: "Catalan is spoken in Catalonia, Valencia, Balearic Islands, Andorra and part of Aragon. 10 million speakers."}},
    {id: "c3", nivell: 1, ca: {titol: "Sardanes", text: "La sardana és el ball tradicional català. La gent balla en rotllana agafats de la mà. Molt comunitari."}, es: {titol: "Sardanas", text: "La sardana és el ball tradicional català. La gent balla en rotllana agafats de la mà. Molt comunitari."}, en: {titol: "Sardanes", text: "The sardana is the traditional Catalan dance. People dance in a circle holding hands. Very communal."}},

    // NIVELL 2 - B2
    {id: "c4", nivell: 2, ca: {titol: "Castells", text: "Els castells són torres humanes tradicionals. La gent s'enfila una sobre l'altra. Patrimoni de la UNESCO."}, es: {titol: "Castells", text: "Els castells són torres humanes tradicionals. La gent s'enfila una sobre l'altra. Patrimoni de la UNESCO."}, en: {titol: "Castells", text: "Castells are traditional human towers. People climb on top of each other. UNESCO Heritage."}},
    {id: "c5", nivell: 2, ca: {titol: "Diada de Sant Jordi", text: "El 23 d'abril es regala una rosa i un llibre. Dia dels enamorats i del llibre. Carrers plens de parades."}, es: {titol: "Día de Sant Jordi", text: "El 23 d'abril es regala una rosa i un llibre. Dia dels enamorats i del llibre. Carrers plens de parades."}, en: {titol: "Sant Jordi's Day", text: "On April 23rd people give a rose and a book. Day of lovers and books. Streets full of stalls."}},
    {id: "c6", nivell: 2, ca: {titol: "Gaudí", text: "Antoni Gaudí és l'arquitecte més famós de Catalunya. Sagrada Família, Parc Güell, Casa Batlló. Modernisme."}, es: {titol: "Gaudí", text: "Antoni Gaudí és l'arquitecte més famós de Catalunya. Sagrada Família, Parc Güell, Casa Batlló. Modernisme."}, en: {titol: "Gaudí", text: "Antoni Gaudí is Catalonia's most famous architect. Sagrada Família, Parc Güell, Casa Batlló. Modernism."}},
    {id: "c7", nivell: 2, ca: {titol: "Costa Brava", text: "La Costa Brava és la costa nord de Catalunya. Cales, platges, pobles de pescadors. Paisatge mediterrani."}, es: {titol: "Costa Brava", text: "La Costa Brava és la costa nord de Catalunya. Cales, platges, pobles de pescadors. Paisatge mediterrani."}, en: {titol: "Costa Brava", text: "The Costa Brava is the northern coast of Catalonia. Coves, beaches, fishing villages. Mediterranean landscape."}},

    // NIVELL 3 - B3
    {id: "c8", nivell: 3, ca: {titol: "La Mercè", text: "La Mercè és la festa major de Barcelona. Hi ha castells, sardanes, concerts, correfoc i gegants. Al setembre."}, es: {titol: "La Mercè", text: "La Mercè és la festa major de Barcelona. Hi ha castells, sardanes, concerts, correfoc i gegants. Al setembre."}, en: {titol: "La Mercè", text: "La Mercè is Barcelona's main festival. There are castells, sardanes, concerts, correfoc and giants. In September."}},
    {id: "c9", nivell: 3, ca: {titol: "Calçotada", text: "La calçotada és un dinar tradicional d'hivern. Es mengen calçots a la brasa amb salsa romesco. Festa popular."}, es: {titol: "Calçotada", text: "La calçotada és un dinar tradicional d'hivern. Es mengen calçots a la brasa amb salsa romesco. Festa popular."}, en: {titol: "Calçotada", text: "Calçotada is a traditional winter meal. People eat grilled calçots with romesco sauce. Popular party."}},
    {id: "c10", nivell: 3, ca: {titol: "Montserrat", text: "Montserrat és una muntanya sagrada amb un monestir. La Moreneta és la verge patrona de Catalunya. Paisatge únic."}, es: {titol: "Montserrat", text: "Montserrat és una muntanya sagrada amb un monestir. La Moreneta és la verge patrona de Catalunya. Paisatge únic."}, en: {titol: "Montserrat", text: "Montserrat is a sacred mountain with a monastery. La Moreneta is Catalonia's patron virgin. Unique landscape."}},
    {id: "c11", nivell: 3, ca: {titol: "Pirineus catalans", text: "Els Pirineus catalans tenen neu a l'hivern i rutes de senderisme a l'estiu. Vall de Boí, Aigüestortes, Parc Nacional."}, es: {titol: "Pirineos catalanes", text: "Els Pirineus catalans tenen neu a l'hivern i rutes de senderisme a l'estiu. Vall de Boí, Aigüestortes, Parc Nacional."}, en: {titol: "Catalan Pyrenees", text: "The Catalan Pyrenees have snow in winter and hiking routes in summer. Vall de Boí, Aigüestortes, National Park."}},
    {id: "c12", nivell: 3, ca: {titol:cuina catalana", text: "La cuina catalana barreja mar i muntanya. Escudella, carn d'olla, marisc, peix, verdura de temporada. Mediterrània i de proximitat."}, es: {titol: "Cocina catalana", text: "La cuina catalana barreja mar i muntanya. Escudella, carn d'olla, marisc, peix, verdura de temporada. Mediterrània i de proximitat."}, en: {titol: "Catalan cuisine", text: "Catalan cuisine mixes sea and mountain. Escudella, carn d'olla, seafood, fish, seasonal vegetables. Mediterranean and local."}}
    }
  ]
};

// Funció per agafar un tip aleatori segons nivell i categoria
function getRandomTip(categoria, nivell) {
  const tips = TIPS_DATA[categoria].filter(t => t.nivell <= nivell);
  return tips[Math.floor(Math.random() * tips.length)];
}

// Funció per obtenir la traducció segons idiomaActual del main.js
function getTipTranslation(tip, idiomaActual) {
  const lang = idiomaActual.split('-')[0]; // ca, es, en
  return tip[lang] || tip.ca;
}
